### ISSUE TITLE
Library album art does not display

### ISSUE THREAD

**Issue by ursasenior** [TT-ReBORN/Georgia-ReBORN#124]
I believe this was functional in the previous versions (2.xx) under the same circumstances.

Most album art seems to work; I have a variety of mostly jpg & png between 100kb to 20 MB.
I have album art [Folder.png](https://cdn.discordapp.com/attachments/622059078973259786/1118753302616748042/Folder.png) in the same network folder that contains an album, but the image does not display in either of the album art panel, nor on the album thumbnail preview in Details view

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/1014472/66a141ff-ba8a-499f-9778-952661cae8e1)

Could this be due to the the specifics of this image file? I could look for more examples in my music library where this occurs

**Comment by TT-ReBORN** [comment]
I have changed the image load method to a different one to fix some issues. It seems the new one does not support other ICC profile than sRGB color space. Your Folder.png has an AdobeRGB ICC embedded which does not make sense because it's a grayscale image. Here is the fixed [Folder.png](https://i.ibb.co/xjSDHPP/Folder.png). 

I will still report this issue to the dev of the Spider Monkey Panel, because there are images with wide color gamut which will take advantage of larger ICC profiles, rather to be limited to the small standard sRGB color space...

**Comment by TT-ReBORN** [comment]
I was wrong, I just checked it seems it does support AdobeRGB ICC profiles.
It seems your Folder.png was a jpeg image but someone has renamed it to a png file, that's why it did not display correctly...

**Comment by TT-ReBORN** [comment]
Updated my previous post, with the correct answer.
