### ISSUE TITLE
Audio Format/Quality Line Not Showing with Newest Release

### ISSUE THREAD

**Issue by sariouso** [TT-ReBORN/Georgia-ReBORN#147]
Hello, the line on the album header in playlists that normally shows format/bit depth/sample rate/album replaygain, etc... doesn't show up on most albums in current release. On some it does but it appears to be pretty random which ones do or don't have it show up. I tried to do a fresh install of foobar in case that was the issue but the problem's still there.

Here's what it looks like: 
![foobar2000_2023-09-04_19-43-15](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/116588808/0d6832e0-ef86-42fd-992b-2533e47e89cc)

Here is my album header settings: 
![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/116588808/0b9ede71-2787-40ff-9d0f-bc5843cff48e)

PS: Thank you for this theme. It's amazing.

**Comment by TT-ReBORN** [comment]
Hi @sariouso,

glad you like the theme. 
What do you mean by newest release? [RC-1 from the Releases page here?](https://github.com/TT-ReBORN/Georgia-ReBORN/releases)

If so, did you try the current [master version from here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip)? 
I think this was fixed some time ago because I can't reproduce it...

-TT

**Comment by sariouso** [comment]
Thank you, using the master fixed it.
