### ISSUE TITLE
Annoying Security Alerts Certificate pop up

### ISSUE THREAD

**Issue by nekomutsuki** [TT-ReBORN/Georgia-ReBORN#148]
Everytime I open foobar this security alert pop up always appears. This pop up always appears even i click yes, no, and view certificate then install the certificate, and this just appears when I install the theme. When I re install the foobar/ completely delete the theme the security alert never appears. Any idea how to block this pop so it will never be appears again? 
![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/36616630/0872471a-9b6f-48ca-bf20-28418d109308)

When the pop up appears repeatedly : 
1. re open foobar
2. open another songs
3. while playing songs

**Comment by TT-ReBORN** [comment]
Hi @nekomutsuki,

this is not an issue or related to the theme, it seems you have issues with your Windows. 
Most of the time this happens when a user has not the correct time/date set in Windows, 
I know this happens on PC's that for example reset their BIOS by doing a CMOS and then try to browse the internet with a wrong date and time.

If that does not help just google the popup message, you will find more information, e.g [this here](https://appuals.com/fix-revocation-information-security-certificate-site-not-available/).

-TT

**Comment by nekomutsuki** [comment]
Hello @TT-ReBORN,

Thanks for the help it's solved now. I just need to uncheck the "check certificate revocation" settings.
