### ISSUE TITLE
Change format of CD image

### ISSUE THREAD

**Issue by PSVLTT** [TT-ReBORN/Georgia-ReBORN#152]
Hi mate.
I want to ask
How can I change CD art spin from CD.png to  CD.JPG... CD(1).JPG...

Thank you!

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

it is not officially supported because JPG format has no transparency and the disc would look bad.
But you can try for yourself, open `gr-setup.js` and go to line ~500. It is the `// * CD ART PATHS` and `// * VINYL DISC ART`
Change the .png to .jpg, save and reload foobar to take effect.

-TT

**Comment by PSVLTT** [comment]
Thank you sir, it is good for me :)
