### ISSUE TITLE
Album Art Placeholder

### ISSUE THREAD

**Issue by PSVLTT** [TT-ReBORN/Georgia-ReBORN#161]
Hi TT,
It's me again.
Can I ask a favor.
Can you change the way of Placeholder Disc Art working?

Like now: If no Disc Art found on album folder (*CD.PNG* etc. files)  = "Show Placeholder if no disc art found” → So I can choose option let Placeholder art render on front art (If I am still understanding exactly) 

But how can I change it to **prioritize** render the CD.JPG…. etc. first, if can found CD.JPG on album folder. If no CD.JPG found… then render PLaceholder with front cover art like now.

I think it is good because we do not waste time to find or make PNG CD art. And because the quality of CD Placeholder made from front cover art is very good, so I believe it will work perfectly with CD art with high resolution image!

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

when I have implemented the special feature when no disc art is found that it will automatically make a placeholder disc art
image from the album cover, I had the exact same idea and tried it. But this does not work on cd.jpg images due to having a special disc art mask that consist of actually two masks. One for the whole disc and one for the inner disc ( for the hole ) 
to be able to mask the album art image nicely onto the disc art placeholder. 

Because of this special mask, it will not work on most images due to having different sizes when the user scanned the disc and created the cd.jpg image. It is complicated to describe in words, but the inner disc hole of those cd.jpg images 
would not fit the mask correctly and it would look ugly to be able to display good results...

Unfortunately there is nothing that can be done.

-TT

**Comment by PSVLTT** [comment]
I got the point. Thank you. I want to ask more. The metadata in Details Tab. How to add more rows tag data. I tried live edit in "blank" you leave it but it is so laggy like something out of RAM or full HDD. I don't sure about it,  a hardware problem or what else.

**Comment by TT-ReBORN** [comment]
You should try the new master version, it has improved metadata grid live editing:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

-TT

**Comment by PSVLTT** [comment]
Dear TT.

It is still laggy and hard to type something in the box

But I can copy and paste to it and it is working now

Thank you very much!

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/142076226/b6fdb337-fcaf-49bd-9ed7-3ac02ef2f67b)

**Comment by TT-ReBORN** [comment]
Glad it is working for you, but I do not have any lag input when typing...

**Comment by PSVLTT** [comment]
Thank you sir 😍
