### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by BooneAllred** [TT-ReBORN/Georgia-ReBORN#184]
Why is the playlist not included in the quick display menu? Why is it only active through the right-click contextual menu?

**Comment by TT-ReBORN** [comment]
Hi @BooneAllred,

it is not needed because the Playlist is the home panel when you start foobar 
and you navigate through the panel buttons in the top menu.

When you click in the top `Menu` on the panel buttons ( `Details`, `Library`, `Biography` or `Lyrics` )
they will be marked as the current active panel. Click on the active marked panel button again, 
and you will automatically go back to the Playlist home panel.

-TT
