### ISSUE TITLE
Red screen error opening foobar2000 after installing on Windows

### ISSUE THREAD

**Issue by TCCBodhi** [TT-ReBORN/Georgia-ReBORN#46]
I'm somewhat a novice at installing themes, but I CAN follow directions. After extracting/installing into the instructed folders, when I attempt to open foobar for the first time, it gives a script error as attached below. If I tell it to continue, I then come to a red screen that says "Aw, crashed" with the 2nd error attached below I'd love to get this theme working, or barring that, back to what I had before (or a default theme). Thanks for any help

![Screenshot 2022-01-20 1](https://user-images.githubusercontent.com/79881959/150288651-05a8a160-e7a0-4d4e-9081-2607c05800ea.png)
![Screenshot 2022-01-20 2](https://user-images.githubusercontent.com/79881959/150288665-d5c86e96-015b-4217-b2ab-a7f10ef3cd37.png)
.

**Comment by TT-ReBORN** [comment]
Hi TCCBodhi,

did you install the standard or portable foobar installation? On first foobar start did you select the Columns UI?
How does your foobar root folder look like? Does the profile folder from the zip file is in the root folder of foobar?

What happens if you try to install it clean again? Never saw or encountered this error...

**Comment by TCCBodhi** [comment]
I run foobar from a PC so it's been installed with a standard install. foobar did not even fully come up when first started, so there was no way to choose Columns UI. My root folder is c-users-myname-AppData-Roaming-foobar2000. The 'georgia-reborn' folder is in the root folder along with images, lyrics, user-components, etc. Playlists-v1.4 has about 32 files in it.

I haven't tried a clean uninstall/reinstall yet, but that will be what is next if the above info doesn't clear anything up. Thanks.

**Comment by TCCBodhi** [comment]
![Screenshot 3](https://user-images.githubusercontent.com/79881959/150419957-77e6c28e-cf8c-47c9-989e-13081e666a50.png)

**Comment by silverwings15** [comment]
you have to make a clean install for sure

**Comment by TCCBodhi** [comment]
Okay then. Thanks for taking a look.

**Comment by TT-ReBORN** [comment]
Instead of using your already installed foobar, install it as portable.

Download the latest foobar2000 from [here](https://www.foobar2000.org/download) and if you double click on the setup file you will be asked during installation if you want to install foobar as portable, click on portable and follow the install instruction for portable installation from [here](https://github.com/TT-ReBORN/Georgia-ReBORN#installation-instructions).

**Comment by silverwings15** [comment]
also backup your current setup first in case you need to revisit it later

**Comment by TCCBodhi** [comment]
I'll give that a shot. Thank you.

**Comment by TCCBodhi** [comment]
I'm at least open after the theme install. Library is still Initializing since I have a HUGE music library, so can't really see anything yet beyong the plain framework, but suspect I'll see it as pictured in your screenshots once the library scanning is finished. I'll let you know once it does.

**Comment by TCCBodhi** [comment]
It finally finished it's indexing a little bit and I'm able to see a theme there under Columns UI. I'll have to play with it more to get some familiarity, but it has the functions I'm looking for at least. Thanks one last time.
