### ISSUE TITLE
Playlist view "Rows" change order of metadata shown

### ISSUE THREAD

**Issue by vfxturjo** [TT-ReBORN/Georgia-ReBORN#93]
Hi. I hope u r fine 😃 

# main issue
Currently the rows show like this:
[Artist Name] - [Album Title] - [Track Title]

I want to be able to change it to my liking. for example:
[Track Title] - [Artist Name]

for that, I think a syntax based option may come in handy. users can just copy paste variables and organize in their way. for example:
`[%title%] - [%artist%]`
etc.

## Another thing:
May be I am making a dumb question... I tried to change things here but I dont see what is changing. could u please tell me what it is for?
![image](https://user-images.githubusercontent.com/44445014/202085734-22ae0737-9894-4986-83dc-87af8a922d8a.png)

**Comment by TT-ReBORN** [comment]
Hi @vfxturjo,

the screenshot you've posted are the playlist settings for the original foobar but not for my theme!
That means you can't do anything there, because my theme has his own playlist. The script can be found
in your foobar2000\profile\georgia-reborn\js\Playlist\main.js

To be able to change the playlist row, you need to modify the code in the main.js in the `// * TITLE init` block here:

```
const title_query = g_properties.show_header ? (pref.showPlaylistTrackNumbers || pref.showPlaylistIndexNumbers ? track_num_query : '') +
(pref.showArtistPlaylistRows && pref.showAlbumPlaylistRows ? `${margin}%artist% - %album% -  %title%[ '('%original artist%' cover)']` :
	pref.showArtistPlaylistRows ? `${margin}%artist% -  %title%[ '('%original artist%' cover)']` :
	pref.showAlbumPlaylistRows  ? `${margin}%album% -  %title%[ '('%original artist%' cover)']` :
`${margin}%title%[ '('%original artist%' cover)']`) : `${margin}   %artist% - %album% - ${showTrackNum} %title%[ '('%original artist%' cover)']`;
```

-TT

**Comment by vfxturjo** [comment]
hi. sorry i didnt understand that my screenshot was for original foobar... I associated it cz I saw the theme was called "Columns-UI"

anyway, I tried to modify the code you mentioned. But for some reason it is not reflected in the theme :(
this is the current code:
![image](https://user-images.githubusercontent.com/44445014/202736707-81ff7b38-3e52-47da-bae8-90e8c9be150e.png)

also I was thinking... if you can make it available with GUI or cliclable/draggable options, that would be really helpful.
thanks in advance!

**Comment by TT-ReBORN** [comment]
That's because you have forgot to add one `- %artist%` tag in your default playlist row state pattern ( the one with your line comment #5123-5129 ). 

If you would use top menu Options > Playlist > Show artist name in all rows
top menu Options > Playlist > Show album title in all rows
and top menu Options > Playlist > Album header > Album header
you would see your new changes.

I don't know why you would change any of these anyways because you already have the playlist header that shows the artist anyways.

Also the options `Show artist name in all rows` and `Show album title in all rows` was intended to use with compilations 
( various artist ) or when using radio ( streaming ). And top menu Options > Playlist > Show artist name on difference is
albums with %album artist% and %track artist%, you could also use it with compilations ( various artist ).

-TT

**Comment by TT-ReBORN** [comment]
Hey @vfxturjo,

I have made things easier and now you don't need to tinker in the config file anymore:
- Added option to customize the playlist track row via top menu Options > Playlist > Track row > Customize track row
  Enter your desired custom pattern for:
    1. When playlist header is being displayed ( default )
    2. When playlist header is deactivated ( Options > Playlist > Album header > Album header )

This is already available in the latest working in progress version, you can get it from here:
https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74#discussion-4190799

-TT
